'use strict';

/**
 * Startdata og migrering for Classic. Kjøres ved oppstart:
 *  1. Sørger for at temaene finnes (idempotent).
 *  2. Backfiller `theme='Klassisk'` på gamle stykker uten tema (migrering).
 *  3. Seeder klassiske stykker kun ved helt tomt bibliotek.
 *  4. Legger til pop-eksempler per tema som ikke allerede finnes (dedupe på
 *     artist + låt), så nye låter kommer inn uten å røre eksisterende (inkl.
 *     Spotify-lenker) og uten dubletter ved ny kjøring.
 *
 * MERK: `spotifyUrl` er bevisst tomt — kjør «Finn Spotify-lenker» i Admin.
 * Pop-metadataen er «startdata» (kjente låter) og kan finpusses i Admin.
 */
const db = require('./lib/db');
const { generateId, now } = require('./lib/helpers');

const SEED_THEMES = [
  { name: 'Klassisk', kind: 'classical' },
  { name: '60-tallet', kind: 'pop' },
  { name: '70-tallet', kind: 'pop' },
  { name: '80-tallet', kind: 'pop' },
  { name: '90-tallet', kind: 'pop' },
  { name: '2000-tallet', kind: 'pop' },
  { name: 'Progrock', kind: 'pop' },
  { name: 'Country', kind: 'pop' },
  { name: 'Flower power', kind: 'pop' },
  { name: 'Hip-hop', kind: 'pop' },
  { name: 'Norsk pop', kind: 'pop' },
  { name: 'Norsk 60-tallspop', kind: 'pop' },
  { name: 'Norske julehits', kind: 'pop' },
];

const SEED_PIECES = [
  { composer: 'Thomas Tallis', year: 1570, epoch: 'Renessanse', work: 'Spem in alium', movement: '' },
  { composer: 'Antonio Vivaldi', year: 1725, epoch: 'Barokk', work: 'De fire årstider – Våren', movement: '1. sats – Allegro' },
  { composer: 'Johann Sebastian Bach', year: 1721, epoch: 'Barokk', work: 'Brandenburgkonsert nr. 3', movement: '1. sats – Allegro' },
  { composer: 'Johann Sebastian Bach', year: 1741, epoch: 'Barokk', work: 'Goldbergvariasjonene', movement: 'Aria' },
  { composer: 'Georg Friedrich Händel', year: 1741, epoch: 'Barokk', work: 'Messias', movement: 'Hallelujah' },
  { composer: 'Wolfgang Amadeus Mozart', year: 1787, epoch: 'Klassisisme', work: 'Eine kleine Nachtmusik', movement: '1. sats – Allegro' },
  { composer: 'Wolfgang Amadeus Mozart', year: 1788, epoch: 'Klassisisme', work: 'Symfoni nr. 40 g-moll', movement: '1. sats – Molto allegro' },
  { composer: 'Joseph Haydn', year: 1791, epoch: 'Klassisisme', work: 'Symfoni nr. 94 «Overraskelsen»', movement: '2. sats – Andante' },
  { composer: 'Ludwig van Beethoven', year: 1808, epoch: 'Klassisisme', work: 'Symfoni nr. 5 c-moll', movement: '1. sats – Allegro con brio' },
  { composer: 'Ludwig van Beethoven', year: 1801, epoch: 'Romantikk', work: 'Måneskinnssonaten', movement: '1. sats – Adagio sostenuto' },
  { composer: 'Franz Schubert', year: 1825, epoch: 'Romantikk', work: 'Ave Maria', movement: '' },
  { composer: 'Frédéric Chopin', year: 1832, epoch: 'Romantikk', work: 'Nocturne Es-dur op. 9 nr. 2', movement: '' },
  { composer: 'Johannes Brahms', year: 1869, epoch: 'Romantikk', work: 'Ungarsk dans nr. 5', movement: '' },
  { composer: 'Edvard Grieg', year: 1875, epoch: 'Romantikk', work: 'Peer Gynt-suite nr. 1', movement: 'I Dovregubbens hall' },
  { composer: 'Edvard Grieg', year: 1875, epoch: 'Romantikk', work: 'Peer Gynt-suite nr. 1', movement: 'Morgenstemning' },
  { composer: 'Pjotr Tsjajkovskij', year: 1876, epoch: 'Romantikk', work: 'Svanesjøen', movement: 'Scene – Moderato' },
  { composer: 'Pjotr Tsjajkovskij', year: 1892, epoch: 'Romantikk', work: 'Nøtteknekkeren', movement: 'Blomstervalsen' },
  { composer: 'Antonín Dvořák', year: 1893, epoch: 'Romantikk', work: 'Symfoni nr. 9 «Fra den nye verden»', movement: '4. sats – Allegro con fuoco' },
  { composer: 'Erik Satie', year: 1888, epoch: 'Impresjonisme', work: 'Gymnopédie nr. 1', movement: '' },
  { composer: 'Claude Debussy', year: 1905, epoch: 'Impresjonisme', work: 'Suite bergamasque', movement: 'Clair de lune' },
  { composer: 'Maurice Ravel', year: 1928, epoch: 'Impresjonisme', work: 'Boléro', movement: '' },
  { composer: 'Gustav Holst', year: 1916, epoch: 'Modernisme', work: 'Planetene', movement: 'Mars, krigsbringeren' },
  { composer: 'Igor Stravinskij', year: 1913, epoch: 'Modernisme', work: 'Vårofferet', movement: 'De unge jentenes dans' },
  { composer: 'George Gershwin', year: 1924, epoch: 'Modernisme', work: 'Rhapsody in Blue', movement: '' },
  { composer: 'Sergej Prokofjev', year: 1935, epoch: 'Modernisme', work: 'Romeo og Julie', movement: 'Ridderdansen' },
  { composer: 'Carl Orff', year: 1936, epoch: 'Modernisme', work: 'Carmina Burana', movement: 'O Fortuna' },
  { composer: 'Dmitrij Sjostakovitsj', year: 1938, epoch: 'Modernisme', work: 'Jazzsuite nr. 2', movement: 'Vals nr. 2' },
  { composer: 'Arvo Pärt', year: 1978, epoch: 'Samtid', work: 'Spiegel im Spiegel', movement: '' },
  { composer: 'Max Richter', year: 2004, epoch: 'Samtid', work: 'The Blue Notebooks', movement: 'On the Nature of Daylight' },
  { composer: 'Ludovico Einaudi', year: 2004, epoch: 'Samtid', work: 'Una Mattina', movement: 'Nuvole bianche' },
];

// Pop-startdata: { artist, album, year, song } (artist→composer, album→epoch, song→work).
const SEED_POP = {
  '60-tallet': [
    { artist: 'The Beatles', album: 'Abbey Road', year: 1969, song: 'Come Together' },
    { artist: 'The Rolling Stones', album: 'Aftermath', year: 1966, song: 'Paint It Black' },
    { artist: 'The Beach Boys', album: 'Pet Sounds', year: 1966, song: 'Wouldn’t It Be Nice' },
    { artist: 'Bob Dylan', album: 'Highway 61 Revisited', year: 1965, song: 'Like a Rolling Stone' },
    { artist: 'The Supremes', album: 'Where Did Our Love Go', year: 1964, song: 'Baby Love' },
    { artist: 'The Beatles', album: 'Rubber Soul', year: 1965, song: 'Norwegian Wood' },
    { artist: 'The Beatles', album: 'Sgt. Pepper’s Lonely Hearts Club Band', year: 1967, song: 'Lucy in the Sky with Diamonds' },
    { artist: 'The Beatles', album: 'A Hard Day’s Night', year: 1964, song: 'A Hard Day’s Night' },
    { artist: 'The Rolling Stones', album: 'Let It Bleed', year: 1969, song: 'Gimme Shelter' },
    { artist: 'The Rolling Stones', album: 'Between the Buttons', year: 1967, song: 'Ruby Tuesday' },
    { artist: 'The Beach Boys', album: 'Surfin’ U.S.A.', year: 1963, song: 'Surfin’ U.S.A.' },
    { artist: 'The Kinks', album: 'Kinks', year: 1964, song: 'You Really Got Me' },
    { artist: 'The Who', album: 'My Generation', year: 1965, song: 'My Generation' },
    { artist: 'The Doors', album: 'The Doors', year: 1967, song: 'Light My Fire' },
    { artist: 'Jimi Hendrix', album: 'Are You Experienced', year: 1967, song: 'Hey Joe' },
    { artist: 'Cream', album: 'Disraeli Gears', year: 1967, song: 'Sunshine of Your Love' },
    { artist: 'The Animals', album: 'The Animals', year: 1964, song: 'The House of the Rising Sun' },
    { artist: 'Simon & Garfunkel', album: 'Sounds of Silence', year: 1966, song: 'The Sound of Silence' },
    { artist: 'Otis Redding', album: 'The Dock of the Bay', year: 1968, song: '(Sittin’ On) The Dock of the Bay' },
    { artist: 'Aretha Franklin', album: 'I Never Loved a Man the Way I Love You', year: 1967, song: 'Respect' },
    { artist: 'Marvin Gaye', album: 'In the Groove', year: 1968, song: 'I Heard It Through the Grapevine' },
    { artist: 'The Temptations', album: 'The Temptations Sing Smokey', year: 1965, song: 'My Girl' },
    { artist: 'Sam Cooke', album: 'Ain’t That Good News', year: 1964, song: 'A Change Is Gonna Come' },
    { artist: 'The Beach Boys', album: 'Summer Days (And Summer Nights!!)', year: 1965, song: 'California Girls' },
    { artist: 'The Righteous Brothers', album: 'You’ve Lost That Lovin’ Feelin’', year: 1965, song: 'You’ve Lost That Lovin’ Feelin’' },
    { artist: 'The Mamas & the Papas', album: 'If You Can Believe Your Eyes and Ears', year: 1966, song: 'Monday, Monday' },
    { artist: 'Creedence Clearwater Revival', album: 'Bayou Country', year: 1969, song: 'Proud Mary' },
    { artist: 'The Zombies', album: 'Odessey and Oracle', year: 1968, song: 'Time of the Season' },
    { artist: 'The Monkees', album: 'More of the Monkees', year: 1967, song: 'I’m a Believer' },
    { artist: 'The Kinks', album: 'The Kink Kontroversy', year: 1965, song: 'Till the End of the Day' },
  ],
  '70-tallet': [
    { artist: 'ABBA', album: 'Arrival', year: 1976, song: 'Dancing Queen' },
    { artist: 'Led Zeppelin', album: 'Led Zeppelin IV', year: 1971, song: 'Stairway to Heaven' },
    { artist: 'Queen', album: 'A Night at the Opera', year: 1975, song: 'Bohemian Rhapsody' },
    { artist: 'Bee Gees', album: 'Saturday Night Fever', year: 1977, song: 'Stayin’ Alive' },
    { artist: 'Fleetwood Mac', album: 'Rumours', year: 1977, song: 'Go Your Own Way' },
    { artist: 'Eagles', album: 'Hotel California', year: 1976, song: 'Hotel California' },
    { artist: 'David Bowie', album: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', year: 1972, song: 'Starman' },
    { artist: 'Pink Floyd', album: 'Wish You Were Here', year: 1975, song: 'Wish You Were Here' },
    { artist: 'Led Zeppelin', album: 'Led Zeppelin IV', year: 1971, song: 'Black Dog' },
    { artist: 'Rod Stewart', album: 'Every Picture Tells a Story', year: 1971, song: 'Maggie May' },
    { artist: 'Elton John', album: 'Goodbye Yellow Brick Road', year: 1973, song: 'Goodbye Yellow Brick Road' },
    { artist: 'Elton John', album: 'Honky Château', year: 1972, song: 'Rocket Man' },
    { artist: 'Stevie Wonder', album: 'Songs in the Key of Life', year: 1976, song: 'Sir Duke' },
    { artist: 'Stevie Wonder', album: 'Talking Book', year: 1972, song: 'Superstition' },
    { artist: 'Marvin Gaye', album: 'What’s Going On', year: 1971, song: 'What’s Going On' },
    { artist: 'The Rolling Stones', album: 'Sticky Fingers', year: 1971, song: 'Brown Sugar' },
    { artist: 'Deep Purple', album: 'Machine Head', year: 1972, song: 'Smoke on the Water' },
    { artist: 'Black Sabbath', album: 'Paranoid', year: 1970, song: 'Paranoid' },
    { artist: 'AC/DC', album: 'Highway to Hell', year: 1979, song: 'Highway to Hell' },
    { artist: 'Queen', album: 'News of the World', year: 1977, song: 'We Will Rock You' },
    { artist: 'ABBA', album: 'ABBA', year: 1975, song: 'Mamma Mia' },
    { artist: 'Bee Gees', album: 'Saturday Night Fever', year: 1977, song: 'Night Fever' },
    { artist: 'Donna Summer', album: 'Bad Girls', year: 1979, song: 'Hot Stuff' },
    { artist: 'Chic', album: 'Risqué', year: 1979, song: 'Good Times' },
    { artist: 'Bruce Springsteen', album: 'Born to Run', year: 1975, song: 'Born to Run' },
    { artist: 'The Clash', album: 'The Clash', year: 1977, song: 'White Riot' },
    { artist: 'Sex Pistols', album: 'Never Mind the Bollocks, Here’s the Sex Pistols', year: 1977, song: 'Anarchy in the U.K.' },
    { artist: 'Blondie', album: 'Parallel Lines', year: 1978, song: 'Heart of Glass' },
    { artist: 'Simon & Garfunkel', album: 'Bridge over Troubled Water', year: 1970, song: 'Bridge over Troubled Water' },
    { artist: 'Fleetwood Mac', album: 'Rumours', year: 1977, song: 'Dreams' },
  ],
  '80-tallet': [
    { artist: 'Michael Jackson', album: 'Thriller', year: 1982, song: 'Billie Jean' },
    { artist: 'Madonna', album: 'Like a Virgin', year: 1984, song: 'Like a Virgin' },
    { artist: 'a-ha', album: 'Hunting High and Low', year: 1985, song: 'Take On Me' },
    { artist: 'Prince', album: 'Purple Rain', year: 1984, song: 'Purple Rain' },
    { artist: 'Whitney Houston', album: 'Whitney Houston', year: 1985, song: 'How Will I Know' },
    { artist: 'Michael Jackson', album: 'Thriller', year: 1982, song: 'Beat It' },
    { artist: 'Michael Jackson', album: 'Bad', year: 1987, song: 'Bad' },
    { artist: 'Madonna', album: 'True Blue', year: 1986, song: 'Papa Don’t Preach' },
    { artist: 'Madonna', album: 'Like a Prayer', year: 1989, song: 'Like a Prayer' },
    { artist: 'Prince', album: '1999', year: 1982, song: '1999' },
    { artist: 'Queen', album: 'The Game', year: 1980, song: 'Another One Bites the Dust' },
    { artist: 'David Bowie', album: 'Let’s Dance', year: 1983, song: 'Let’s Dance' },
    { artist: 'The Police', album: 'Synchronicity', year: 1983, song: 'Every Breath You Take' },
    { artist: 'Dire Straits', album: 'Brothers in Arms', year: 1985, song: 'Money for Nothing' },
    { artist: 'U2', album: 'The Joshua Tree', year: 1987, song: 'With or Without You' },
    { artist: 'Bon Jovi', album: 'Slippery When Wet', year: 1986, song: 'Livin’ on a Prayer' },
    { artist: 'Guns N’ Roses', album: 'Appetite for Destruction', year: 1987, song: 'Sweet Child o’ Mine' },
    { artist: 'Cyndi Lauper', album: 'She’s So Unusual', year: 1983, song: 'Girls Just Want to Have Fun' },
    { artist: 'Whitney Houston', album: 'Whitney', year: 1987, song: 'I Wanna Dance with Somebody (Who Loves Me)' },
    { artist: 'Tears for Fears', album: 'Songs from the Big Chair', year: 1985, song: 'Everybody Wants to Rule the World' },
    { artist: 'Depeche Mode', album: 'Music for the Masses', year: 1987, song: 'Never Let Me Down Again' },
    { artist: 'Eurythmics', album: 'Sweet Dreams (Are Made of This)', year: 1983, song: 'Sweet Dreams (Are Made of This)' },
    { artist: 'Duran Duran', album: 'Rio', year: 1982, song: 'Hungry Like the Wolf' },
    { artist: 'Toto', album: 'Toto IV', year: 1982, song: 'Africa' },
    { artist: 'Journey', album: 'Escape', year: 1981, song: 'Don’t Stop Believin’' },
    { artist: 'Phil Collins', album: 'Face Value', year: 1981, song: 'In the Air Tonight' },
    { artist: 'Wham!', album: 'Make It Big', year: 1984, song: 'Wake Me Up Before You Go-Go' },
    { artist: 'New Order', album: 'Substance', year: 1987, song: 'Blue Monday' },
    { artist: 'AC/DC', album: 'Back in Black', year: 1980, song: 'Back in Black' },
    { artist: 'Kate Bush', album: 'Hounds of Love', year: 1985, song: 'Running Up That Hill (A Deal with God)' },
  ],
  '90-tallet': [
    { artist: 'Nirvana', album: 'Nevermind', year: 1991, song: 'Smells Like Teen Spirit' },
    { artist: 'Oasis', album: '(What’s the Story) Morning Glory?', year: 1995, song: 'Wonderwall' },
    { artist: 'Spice Girls', album: 'Spice', year: 1996, song: 'Wannabe' },
    { artist: 'Backstreet Boys', album: 'Backstreet’s Back', year: 1997, song: 'Everybody (Backstreet’s Back)' },
    { artist: 'TLC', album: 'CrazySexyCool', year: 1994, song: 'Waterfalls' },
    { artist: 'Nirvana', album: 'Nevermind', year: 1991, song: 'Come as You Are' },
    { artist: 'Radiohead', album: 'OK Computer', year: 1997, song: 'Paranoid Android' },
    { artist: 'Radiohead', album: 'The Bends', year: 1995, song: 'Fake Plastic Trees' },
    { artist: 'Oasis', album: 'Definitely Maybe', year: 1994, song: 'Live Forever' },
    { artist: 'Blur', album: 'Parklife', year: 1994, song: 'Girls & Boys' },
    { artist: 'Pearl Jam', album: 'Ten', year: 1991, song: 'Alive' },
    { artist: 'Red Hot Chili Peppers', album: 'Blood Sugar Sex Magik', year: 1991, song: 'Under the Bridge' },
    { artist: 'Metallica', album: 'Metallica', year: 1991, song: 'Enter Sandman' },
    { artist: 'Green Day', album: 'Dookie', year: 1994, song: 'Basket Case' },
    { artist: 'The Cranberries', album: 'No Need to Argue', year: 1994, song: 'Zombie' },
    { artist: 'Alanis Morissette', album: 'Jagged Little Pill', year: 1995, song: 'You Oughta Know' },
    { artist: 'Britney Spears', album: '...Baby One More Time', year: 1999, song: '...Baby One More Time' },
    { artist: 'Backstreet Boys', album: 'Millennium', year: 1999, song: 'I Want It That Way' },
    { artist: 'Spice Girls', album: 'Spice', year: 1996, song: 'Say You’ll Be There' },
    { artist: 'Whitney Houston', album: 'The Bodyguard', year: 1992, song: 'I Will Always Love You' },
    { artist: 'Mariah Carey', album: 'Music Box', year: 1993, song: 'Hero' },
    { artist: 'Céline Dion', album: 'Falling into You', year: 1996, song: 'Because You Loved Me' },
    { artist: '2Pac', album: 'All Eyez on Me', year: 1996, song: 'California Love' },
    { artist: 'The Notorious B.I.G.', album: 'Life After Death', year: 1997, song: 'Mo Money Mo Problems' },
    { artist: 'Beck', album: 'Odelay', year: 1996, song: 'Where It’s At' },
    { artist: 'Beastie Boys', album: 'Ill Communication', year: 1994, song: 'Sabotage' },
    { artist: 'Madonna', album: 'Ray of Light', year: 1998, song: 'Frozen' },
    { artist: 'U2', album: 'Achtung Baby', year: 1991, song: 'One' },
    { artist: 'R.E.M.', album: 'Automatic for the People', year: 1992, song: 'Everybody Hurts' },
    { artist: 'Destiny’s Child', album: 'The Writing’s on the Wall', year: 1999, song: 'Bills, Bills, Bills' },
  ],
  '2000-tallet': [
    { artist: 'Coldplay', album: 'A Rush of Blood to the Head', year: 2002, song: 'Clocks' },
    { artist: 'Beyoncé', album: 'Dangerously in Love', year: 2003, song: 'Crazy in Love' },
    { artist: 'Amy Winehouse', album: 'Back to Black', year: 2006, song: 'Rehab' },
    { artist: 'The White Stripes', album: 'Elephant', year: 2003, song: 'Seven Nation Army' },
    { artist: 'Gnarls Barkley', album: 'St. Elsewhere', year: 2006, song: 'Crazy' },
    { artist: 'Coldplay', album: 'X&Y', year: 2005, song: 'Fix You' },
    { artist: 'Coldplay', album: 'Viva la Vida or Death and All His Friends', year: 2008, song: 'Viva la Vida' },
    { artist: 'Eminem', album: 'The Marshall Mathers LP', year: 2000, song: 'Stan' },
    { artist: 'Eminem', album: 'The Eminem Show', year: 2002, song: 'Without Me' },
    { artist: 'OutKast', album: 'Speakerboxxx/The Love Below', year: 2003, song: 'Hey Ya!' },
    { artist: 'Kanye West', album: 'Graduation', year: 2007, song: 'Stronger' },
    { artist: 'Jay-Z', album: 'The Blueprint', year: 2001, song: 'Izzo (H.O.V.A.)' },
    { artist: '50 Cent', album: 'Get Rich or Die Tryin’', year: 2003, song: 'In da Club' },
    { artist: 'Rihanna', album: 'Good Girl Gone Bad', year: 2007, song: 'Umbrella' },
    { artist: 'Lady Gaga', album: 'The Fame', year: 2008, song: 'Poker Face' },
    { artist: 'Britney Spears', album: 'In the Zone', year: 2003, song: 'Toxic' },
    { artist: 'Beyoncé', album: 'B’Day', year: 2006, song: 'Irreplaceable' },
    { artist: 'Justin Timberlake', album: 'FutureSex/LoveSounds', year: 2006, song: 'SexyBack' },
    { artist: 'The Killers', album: 'Hot Fuss', year: 2004, song: 'Mr. Brightside' },
    { artist: 'Franz Ferdinand', album: 'Franz Ferdinand', year: 2004, song: 'Take Me Out' },
    { artist: 'Arctic Monkeys', album: 'Whatever People Say I Am, That’s What I’m Not', year: 2006, song: 'I Bet You Look Good on the Dancefloor' },
    { artist: 'Kings of Leon', album: 'Only by the Night', year: 2008, song: 'Sex on Fire' },
    { artist: 'Green Day', album: 'American Idiot', year: 2004, song: 'American Idiot' },
    { artist: 'U2', album: 'All That You Can’t Leave Behind', year: 2000, song: 'Beautiful Day' },
    { artist: 'Linkin Park', album: 'Hybrid Theory', year: 2000, song: 'In the End' },
    { artist: 'Nelly', album: 'Nellyville', year: 2002, song: 'Hot in Herre' },
    { artist: 'Gwen Stefani', album: 'Love. Angel. Music. Baby.', year: 2004, song: 'Hollaback Girl' },
    { artist: 'Snow Patrol', album: 'Eyes Open', year: 2006, song: 'Chasing Cars' },
    { artist: 'Norah Jones', album: 'Come Away with Me', year: 2002, song: 'Don’t Know Why' },
    { artist: 'MGMT', album: 'Oracular Spectacular', year: 2007, song: 'Kids' },
  ],
  Progrock: [
    { artist: 'Pink Floyd', album: 'The Dark Side of the Moon', year: 1973, song: 'Money' },
    { artist: 'Yes', album: 'Fragile', year: 1971, song: 'Roundabout' },
    { artist: 'Genesis', album: 'Selling England by the Pound', year: 1973, song: 'Firth of Fifth' },
    { artist: 'King Crimson', album: 'In the Court of the Crimson King', year: 1969, song: '21st Century Schizoid Man' },
    { artist: 'Rush', album: 'Moving Pictures', year: 1981, song: 'Tom Sawyer' },
    { artist: 'Pink Floyd', album: 'Wish You Were Here', year: 1975, song: 'Shine On You Crazy Diamond' },
    { artist: 'Pink Floyd', album: 'The Wall', year: 1979, song: 'Comfortably Numb' },
    { artist: 'Pink Floyd', album: 'Animals', year: 1977, song: 'Dogs' },
    { artist: 'Genesis', album: 'Foxtrot', year: 1972, song: 'Supper’s Ready' },
    { artist: 'Genesis', album: 'The Lamb Lies Down on Broadway', year: 1974, song: 'The Lamb Lies Down on Broadway' },
    { artist: 'Yes', album: 'Close to the Edge', year: 1972, song: 'Close to the Edge' },
    { artist: 'Yes', album: 'Going for the One', year: 1977, song: 'Wonderous Stories' },
    { artist: 'King Crimson', album: 'Larks’ Tongues in Aspic', year: 1973, song: 'Larks’ Tongues in Aspic, Part One' },
    { artist: 'Rush', album: '2112', year: 1976, song: '2112' },
    { artist: 'Rush', album: 'Hemispheres', year: 1978, song: 'La Villa Strangiato' },
    { artist: 'Emerson, Lake & Palmer', album: 'Brain Salad Surgery', year: 1973, song: 'Karn Evil 9' },
    { artist: 'Emerson, Lake & Palmer', album: 'Trilogy', year: 1972, song: 'From the Beginning' },
    { artist: 'Jethro Tull', album: 'Aqualung', year: 1971, song: 'Aqualung' },
    { artist: 'Jethro Tull', album: 'Thick as a Brick', year: 1972, song: 'Thick as a Brick' },
    { artist: 'Camel', album: 'Mirage', year: 1974, song: 'Lady Fantasy' },
    { artist: 'Gentle Giant', album: 'Octopus', year: 1972, song: 'Knots' },
    { artist: 'Van der Graaf Generator', album: 'Pawn Hearts', year: 1971, song: 'Man-Erg' },
    { artist: 'The Moody Blues', album: 'Days of Future Passed', year: 1967, song: 'Nights in White Satin' },
    { artist: 'Procol Harum', album: 'Procol Harum', year: 1967, song: 'A Whiter Shade of Pale' },
    { artist: 'Marillion', album: 'Misplaced Childhood', year: 1985, song: 'Kayleigh' },
    { artist: 'Dream Theater', album: 'Images and Words', year: 1992, song: 'Pull Me Under' },
    { artist: 'Porcupine Tree', album: 'In Absentia', year: 2002, song: 'Blackest Eyes' },
    { artist: 'Tool', album: 'Lateralus', year: 2001, song: 'Schism' },
    { artist: 'Frank Zappa', album: 'Hot Rats', year: 1969, song: 'Peaches en Regalia' },
    { artist: 'Supertramp', album: 'Crime of the Century', year: 1974, song: 'Dreamer' },
  ],
  Country: [
    { artist: 'Johnny Cash', album: 'At Folsom Prison', year: 1968, song: 'Folsom Prison Blues' },
    { artist: 'Dolly Parton', album: 'Jolene', year: 1974, song: 'Jolene' },
    { artist: 'Willie Nelson', album: 'Red Headed Stranger', year: 1975, song: 'Blue Eyes Crying in the Rain' },
    { artist: 'Kenny Rogers', album: 'The Gambler', year: 1978, song: 'The Gambler' },
    { artist: 'Patsy Cline', album: 'Patsy Cline Showcase', year: 1961, song: 'Crazy' },
    { artist: 'Johnny Cash', album: 'Ring of Fire: The Best of Johnny Cash', year: 1963, song: 'Ring of Fire' },
    { artist: 'Dolly Parton', album: 'Jolene', year: 1974, song: 'I Will Always Love You' },
    { artist: 'Willie Nelson', album: 'Stardust', year: 1978, song: 'Georgia on My Mind' },
    { artist: 'Kenny Rogers', album: 'Greatest Hits', year: 1980, song: 'Lady' },
    { artist: 'Hank Williams', album: 'Moanin’ the Blues', year: 1952, song: 'I’m So Lonesome I Could Cry' },
    { artist: 'Tammy Wynette', album: 'Stand by Your Man', year: 1968, song: 'Stand by Your Man' },
    { artist: 'Loretta Lynn', album: 'Coal Miner’s Daughter', year: 1970, song: 'Coal Miner’s Daughter' },
    { artist: 'Merle Haggard', album: 'Okie from Muskogee', year: 1969, song: 'Okie from Muskogee' },
    { artist: 'George Jones', album: 'I Am What I Am', year: 1980, song: 'He Stopped Loving Her Today' },
    { artist: 'Charlie Rich', album: 'Behind Closed Doors', year: 1973, song: 'Behind Closed Doors' },
    { artist: 'Glen Campbell', album: 'Wichita Lineman', year: 1968, song: 'Wichita Lineman' },
    { artist: 'John Denver', album: 'Poems, Prayers & Promises', year: 1971, song: 'Take Me Home, Country Roads' },
    { artist: 'Kris Kristofferson', album: 'The Silver Tongued Devil and I', year: 1971, song: 'Me and Bobby McGee' },
    { artist: 'Garth Brooks', album: 'No Fences', year: 1990, song: 'Friends in Low Places' },
    { artist: 'Shania Twain', album: 'Come On Over', year: 1997, song: 'Man! I Feel Like a Woman!' },
    { artist: 'Shania Twain', album: 'Come On Over', year: 1997, song: 'You’re Still the One' },
    { artist: 'Alan Jackson', album: 'A Lot About Livin’ (And a Little ’bout Love)', year: 1992, song: 'Chattahoochee' },
    { artist: 'Faith Hill', album: 'Breathe', year: 1999, song: 'Breathe' },
    { artist: 'Tim McGraw', album: 'Not a Moment Too Soon', year: 1994, song: 'Don’t Take the Girl' },
    { artist: 'Dixie Chicks', album: 'Fly', year: 1999, song: 'Cowboy Take Me Away' },
    { artist: 'Johnny Cash', album: 'American IV: The Man Comes Around', year: 2002, song: 'Hurt' },
    { artist: 'Taylor Swift', album: 'Fearless', year: 2008, song: 'Love Story' },
    { artist: 'Carrie Underwood', album: 'Some Hearts', year: 2005, song: 'Before He Cheats' },
    { artist: 'Brad Paisley', album: 'Time Well Wasted', year: 2005, song: 'Alcohol' },
    { artist: 'Keith Urban', album: 'Golden Road', year: 2002, song: 'Somebody Like You' },
  ],
  'Flower power': [
    { artist: 'Scott McKenzie', album: 'The Voice of Scott McKenzie', year: 1967, song: 'San Francisco' },
    { artist: 'Jimi Hendrix', album: 'Are You Experienced', year: 1967, song: 'Purple Haze' },
    { artist: 'The Mamas & the Papas', album: 'If You Can Believe Your Eyes and Ears', year: 1966, song: 'California Dreamin’' },
    { artist: 'The Byrds', album: 'Mr. Tambourine Man', year: 1965, song: 'Mr. Tambourine Man' },
    { artist: 'Jefferson Airplane', album: 'Surrealistic Pillow', year: 1967, song: 'White Rabbit' },
    { artist: 'The Beatles', album: 'Magical Mystery Tour', year: 1967, song: 'All You Need Is Love' },
    { artist: 'The Beatles', album: 'Revolver', year: 1966, song: 'Tomorrow Never Knows' },
    { artist: 'Jefferson Airplane', album: 'Surrealistic Pillow', year: 1967, song: 'Somebody to Love' },
    { artist: 'The Byrds', album: 'Fifth Dimension', year: 1966, song: 'Eight Miles High' },
    { artist: 'The Doors', album: 'The Doors', year: 1967, song: 'Break On Through (To the Other Side)' },
    { artist: 'The Turtles', album: 'Happy Together', year: 1967, song: 'Happy Together' },
    { artist: 'Donovan', album: 'Sunshine Superman', year: 1966, song: 'Sunshine Superman' },
    { artist: 'The Youngbloods', album: 'The Youngbloods', year: 1967, song: 'Get Together' },
    { artist: 'Sly and the Family Stone', album: 'Stand!', year: 1969, song: 'Everyday People' },
    { artist: 'The 5th Dimension', album: 'The Age of Aquarius', year: 1969, song: 'Aquarius/Let the Sunshine In' },
    { artist: 'The Beach Boys', album: 'Smiley Smile', year: 1967, song: 'Good Vibrations' },
    { artist: 'Buffalo Springfield', album: 'Buffalo Springfield', year: 1967, song: 'For What It’s Worth' },
    { artist: 'Steppenwolf', album: 'Steppenwolf', year: 1968, song: 'Born to Be Wild' },
    { artist: 'Iron Butterfly', album: 'In-A-Gadda-Da-Vida', year: 1968, song: 'In-A-Gadda-Da-Vida' },
    { artist: 'Big Brother and the Holding Company', album: 'Cheap Thrills', year: 1968, song: 'Piece of My Heart' },
    { artist: 'The Kinks', album: 'Something Else by the Kinks', year: 1967, song: 'Waterloo Sunset' },
    { artist: 'Traffic', album: 'Mr. Fantasy', year: 1967, song: 'Dear Mr. Fantasy' },
    { artist: 'Small Faces', album: 'Ogdens’ Nut Gone Flake', year: 1968, song: 'Itchycoo Park' },
    { artist: 'The Lovin’ Spoonful', album: 'Hums of the Lovin’ Spoonful', year: 1966, song: 'Summer in the City' },
    { artist: 'Creedence Clearwater Revival', album: 'Green River', year: 1969, song: 'Bad Moon Rising' },
    { artist: 'Grateful Dead', album: 'Workingman’s Dead', year: 1970, song: 'Uncle John’s Band' },
    { artist: 'Crosby, Stills, Nash & Young', album: 'Déjà Vu', year: 1970, song: 'Woodstock' },
    { artist: 'Melanie', album: 'Candles in the Rain', year: 1970, song: 'Lay Down (Candles in the Rain)' },
    { artist: 'The Beatles', album: 'Yellow Submarine', year: 1969, song: 'Yellow Submarine' },
    { artist: 'Country Joe and the Fish', album: 'Electric Music for the Mind and Body', year: 1967, song: 'Not So Sweet Martha Lorraine' },
  ],
  'Hip-hop': [
    { artist: 'The Notorious B.I.G.', album: 'Ready to Die', year: 1994, song: 'Juicy' },
    { artist: 'Dr. Dre', album: 'The Chronic', year: 1992, song: 'Nuthin’ but a ‘G’ Thang' },
    { artist: 'Eminem', album: 'The Marshall Mathers LP', year: 2000, song: 'The Real Slim Shady' },
    { artist: 'Kanye West', album: 'The College Dropout', year: 2004, song: 'Through the Wire' },
    { artist: 'Kendrick Lamar', album: 'good kid, m.A.A.d city', year: 2012, song: 'Swimming Pools (Drank)' },
    { artist: 'Grandmaster Flash and the Furious Five', album: 'The Message', year: 1982, song: 'The Message' },
    { artist: 'Run-D.M.C.', album: 'Raising Hell', year: 1986, song: 'Walk This Way' },
    { artist: 'Beastie Boys', album: 'Licensed to Ill', year: 1986, song: '(You Gotta) Fight for Your Right (To Party!)' },
    { artist: 'Public Enemy', album: 'It Takes a Nation of Millions to Hold Us Back', year: 1988, song: 'Bring the Noise' },
    { artist: 'N.W.A', album: 'Straight Outta Compton', year: 1988, song: 'Straight Outta Compton' },
    { artist: '2Pac', album: 'All Eyez on Me', year: 1996, song: 'California Love' },
    { artist: 'The Notorious B.I.G.', album: 'Life After Death', year: 1997, song: 'Hypnotize' },
    { artist: 'Snoop Dogg', album: 'Doggystyle', year: 1993, song: 'Gin and Juice' },
    { artist: 'Wu-Tang Clan', album: 'Enter the Wu-Tang (36 Chambers)', year: 1993, song: 'C.R.E.A.M.' },
    { artist: 'A Tribe Called Quest', album: 'The Low End Theory', year: 1991, song: 'Scenario' },
    { artist: 'Nas', album: 'Illmatic', year: 1994, song: 'N.Y. State of Mind' },
    { artist: 'Jay-Z', album: 'The Blueprint', year: 2001, song: 'Izzo (H.O.V.A.)' },
    { artist: 'Missy Elliott', album: 'Miss E... So Addictive', year: 2001, song: 'Get Ur Freak On' },
    { artist: 'OutKast', album: 'Stankonia', year: 2000, song: 'Ms. Jackson' },
    { artist: '50 Cent', album: 'Get Rich or Die Tryin’', year: 2003, song: 'In da Club' },
    { artist: 'Eminem', album: '8 Mile', year: 2002, song: 'Lose Yourself' },
    { artist: 'Kanye West', album: 'Late Registration', year: 2005, song: 'Gold Digger' },
    { artist: 'Kanye West', album: 'My Beautiful Dark Twisted Fantasy', year: 2010, song: 'Power' },
    { artist: 'Jay-Z', album: 'The Black Album', year: 2003, song: '99 Problems' },
    { artist: 'Lil Wayne', album: 'Tha Carter III', year: 2008, song: 'Lollipop' },
    { artist: 'Kendrick Lamar', album: 'To Pimp a Butterfly', year: 2015, song: 'Alright' },
    { artist: 'Drake', album: 'Take Care', year: 2011, song: 'Headlines' },
    { artist: 'Dr. Dre', album: '2001', year: 1999, song: 'Still D.R.E.' },
    { artist: 'Cardi B', album: 'Invasion of Privacy', year: 2018, song: 'Bodak Yellow' },
    { artist: 'The Sugarhill Gang', album: 'Sugarhill Gang', year: 1980, song: 'Rapper’s Delight' },
  ],
  'Norsk pop': [
    { artist: 'a-ha', album: 'Hunting High and Low', year: 1985, song: 'The Sun Always Shines on T.V.' },
    { artist: 'Röyksopp', album: 'Melody A.M.', year: 2001, song: 'Eple' },
    { artist: 'Kings of Convenience', album: 'Quiet Is the New Loud', year: 2001, song: 'Toxic Girl' },
    { artist: 'Kygo', album: 'Cloud Nine', year: 2016, song: 'Firestone' },
    { artist: 'Aurora', album: 'All My Demons Greeting Me as a Friend', year: 2016, song: 'Runaway' },
    { artist: 'a-ha', album: 'Hunting High and Low', year: 1985, song: 'Hunting High and Low' },
    { artist: 'a-ha', album: 'Scoundrel Days', year: 1986, song: 'Cry Wolf' },
    { artist: 'a-ha', album: 'Stay on These Roads', year: 1988, song: 'Stay on These Roads' },
    { artist: 'Röyksopp', album: 'The Understanding', year: 2005, song: 'What Else Is There?' },
    { artist: 'Röyksopp', album: 'Junior', year: 2009, song: 'Happy Up Here' },
    { artist: 'Kygo', album: 'Cloud Nine', year: 2016, song: 'Stole the Show' },
    { artist: 'Kygo', album: 'Kids in Love', year: 2017, song: 'It Ain’t Me' },
    { artist: 'Sigrid', album: 'Sucker Punch', year: 2019, song: 'Don’t Kill My Vibe' },
    { artist: 'Sigrid', album: 'Sucker Punch', year: 2019, song: 'Strangers' },
    { artist: 'Aurora', album: 'Infections of a Different Kind – Step 1', year: 2018, song: 'Queendom' },
    { artist: 'Highasakite', album: 'Silent Treatment', year: 2014, song: 'Since Last Wednesday' },
    { artist: 'Madcon', album: 'So Dark the Con of Man', year: 2007, song: 'Beggin’' },
    { artist: 'Alan Walker', album: 'Faded', year: 2015, song: 'Faded' },
    { artist: 'Astrid S', album: 'Astrid S', year: 2017, song: 'Hurts So Good' },
    { artist: 'Marcus & Martinus', album: 'Together', year: 2016, song: 'Elektrisk' },
    { artist: 'Ylvis', album: 'The Fox (What Does the Fox Say?)', year: 2013, song: 'The Fox (What Does the Fox Say?)' },
    { artist: 'deLillos', album: 'Før var det morsomt med sne', year: 1986, song: 'Neste sommer' },
    { artist: 'DumDum Boys', album: 'Splitter pine', year: 1988, song: 'Enkel og grei' },
    { artist: 'Postgirobygget', album: 'Idyll', year: 1996, song: 'Idyll' },
    { artist: 'Lene Marlin', album: 'Playing My Game', year: 1999, song: 'Sitting Down Here' },
    { artist: 'Maria Mena', album: 'White Turns Blue', year: 2004, song: 'You’re the Only One' },
    { artist: 'Kurt Nilsen', album: 'I', year: 2003, song: 'She’s So High' },
    { artist: 'Morten Abel', album: 'Some of These Days', year: 1999, song: 'Be My Lover' },
    { artist: 'Sondre Lerche', album: 'Faces Down', year: 2001, song: 'Sleep on Needles' },
    { artist: 'Susanne Sundfør', album: 'Ten Love Songs', year: 2015, song: 'Fade Away' },
  ],
  // Norsk populærmusikk fra 60-tallet. MERK: mye ble utgitt som singler, så
  // «album» = utgivelsens/singelens navn, og enkelte årstall er omtrentlige —
  // verifiser/juster i Admin. Artist + låt er det som betyr mest for spillet.
  'Norsk 60-tallspop': [
    { artist: 'Nora Brockstedt', album: 'Voi Voi', year: 1960, song: 'Voi Voi' },
    { artist: 'Nora Brockstedt', album: 'Sommer i Palma', year: 1961, song: 'Sommer i Palma' },
    { artist: 'Nora Brockstedt', album: 'Augustin', year: 1960, song: 'Augustin' },
    { artist: 'Wenche Myhre', album: 'La meg være ung', year: 1965, song: 'La meg være ung' },
    { artist: 'Wenche Myhre', album: 'Gi meg en cowboy til mann', year: 1965, song: 'Gi meg en cowboy til mann' },
    { artist: 'Wenche Myhre', album: 'Vær ikke redd', year: 1963, song: 'Vær ikke redd' },
    { artist: 'Wenche Myhre', album: 'Byen sover', year: 1966, song: 'Byen sover' },
    { artist: 'Kirsti Sparboe', album: 'Karusell', year: 1965, song: 'Karusell' },
    { artist: 'Kirsti Sparboe', album: 'Ronny', year: 1966, song: 'Ronny' },
    { artist: 'Kirsti Sparboe', album: 'Dukkemann', year: 1967, song: 'Dukkemann' },
    { artist: 'Kirsti Sparboe', album: 'Å, for et deilig vær', year: 1969, song: 'Å, for et deilig vær' },
    { artist: 'The Pussycats', album: 'Rør ved meg', year: 1966, song: 'Rør ved meg' },
    { artist: 'The Pussycats', album: 'The Cat', year: 1966, song: 'The Cat' },
    { artist: 'The Vanguards', album: 'Susan', year: 1966, song: 'Susan' },
    { artist: 'Inger Jacobsen', album: 'Kom sol, kom regn', year: 1962, song: 'Kom sol, kom regn' },
    { artist: 'Anita Thallaug', album: 'Solhverv', year: 1963, song: 'Solhverv' },
    { artist: 'Åse Kleveland', album: 'Intet er nytt under solen', year: 1966, song: 'Intet er nytt under solen' },
    { artist: 'Arne Bendiksen', album: 'Spiral', year: 1964, song: 'Spiral' },
  ],
  // Norske julehits / julesanger. MERK: dette temaet blander gamle salmer/viser
  // (opphavsår, «artist» = forfatter/komponist eller «Tradisjonell») med nyere
  // innspillinger (artist = utøver). «Album» og «årstall» er derfor tolkende og
  // omtrentlige — juster i Admin. Artist + låt er det viktigste for gjenkjenning.
  'Norske julehits': [
    { artist: 'Alf Prøysen', album: 'Musevisa', year: 1946, song: 'Musevisa' },
    { artist: 'Alf Prøysen', album: 'Julekveldsvisa', year: 1951, song: 'Julekveldsvisa' },
    { artist: 'Alf Prøysen', album: 'Romjulsdrøm', year: 1965, song: 'Romjulsdrøm' },
    { artist: 'Oslo Gospel Choir', album: 'En stjerne skinner i natt', year: 1993, song: 'En stjerne skinner i natt' },
    { artist: 'Oslo Gospel Choir', album: 'Barn av lyset', year: 1996, song: 'Barn av lyset' },
    { artist: 'Sissel Kyrkjebø', album: 'Innerst i sjelen', year: 1994, song: 'Innerst i sjelen' },
    { artist: 'Sissel Kyrkjebø & Odd Nordstoga', album: 'Kvelden før julekvelden', year: 2010, song: 'Kvelden før julekvelden' },
    { artist: 'Jakob Sande', album: 'Det lyser i stille grender', year: 1931, song: 'Det lyser i stille grender' },
    { artist: 'Margrethe Munthe', album: 'På låven sitter nissen', year: 1911, song: 'På låven sitter nissen' },
    { artist: 'Eyvind Skeie', album: 'Tenn lys', year: 1984, song: 'Tenn lys' },
    { artist: 'Marie Wexelsen', album: 'Jeg er så glad hver julekveld', year: 1859, song: 'Jeg er så glad hver julekveld' },
    { artist: 'Johan Krohn', album: 'Du grønne, glitrende tre, god dag', year: 1863, song: 'Du grønne, glitrende tre, god dag' },
    { artist: 'Elias Blix', album: 'No koma Guds englar', year: 1875, song: 'No koma Guds englar' },
    { artist: 'B.S. Ingemann', album: 'Deilig er jorden', year: 1850, song: 'Deilig er jorden' },
    { artist: 'Franz Gruber', album: 'Glade jul, hellige jul', year: 1818, song: 'Glade jul, hellige jul' },
    { artist: 'Emmy Köhler', album: 'Nå tennes tusen julelys', year: 1898, song: 'Nå tennes tusen julelys' },
    { artist: 'Hans Adolph Brorson', album: 'Mitt hjerte alltid vanker', year: 1732, song: 'Mitt hjerte alltid vanker' },
    { artist: 'Hans Adolph Brorson', album: 'Her kommer dine arme små', year: 1732, song: 'Her kommer dine arme små' },
    { artist: 'N.F.S. Grundtvig', album: 'Det kimer nå til julefest', year: 1817, song: 'Det kimer nå til julefest' },
    { artist: 'N.F.S. Grundtvig', album: 'Kimer, I klokker', year: 1856, song: 'Kimer, I klokker' },
    { artist: 'B.S. Ingemann', album: 'Deilig er den himmel blå', year: 1810, song: 'Deilig er den himmel blå' },
    { artist: 'N.F.S. Grundtvig', album: 'Fra fjord og fjære', year: 1856, song: 'Fra fjord og fjære' },
    { artist: 'Tradisjonell', album: 'Så går vi rundt om en enebærbusk', year: 1850, song: 'Så går vi rundt om en enebærbusk' },
    { artist: 'Tradisjonell', album: 'Et barn er født i Betlehem', year: 1600, song: 'Et barn er født i Betlehem' },
    { artist: 'Tradisjonell', album: 'Å, jul med din glede', year: 1900, song: 'Å, jul med din glede' },
    { artist: 'Tradisjonell', album: 'Det hev ei rose sprunge', year: 1599, song: 'Det hev ei rose sprunge' },
    { artist: 'Tradisjonell', album: 'Eg synger julekvad', year: 1328, song: 'Eg synger julekvad' },
    { artist: 'Tradisjonell', album: 'O du hellige', year: 1816, song: 'O du hellige' },
    { artist: 'Tradisjonell', album: 'Rudolf er rød på nesen', year: 1949, song: 'Rudolf er rød på nesen' },
    { artist: 'Tradisjonell', album: 'Nå vandrer fra hver en verdenskrok', year: 1856, song: 'Nå vandrer fra hver en verdenskrok' },
  ],
};

function normKey(s) {
  return String(s == null ? '' : s).toLowerCase().replace(/\s+/g, ' ').trim();
}

function seedIfEmpty() {
  // 1. Temaer (idempotent)
  for (const t of SEED_THEMES) {
    if (!db.findOne('themes', { name: t.name })) {
      db.upsertEntity('themes', 'theme', generateId(), { ...t, createdAt: now() });
    }
  }

  // 2. Migrering: gamle stykker uten tema → «Klassisk»
  const pieces = db.listEntities('pieces');
  let migrated = 0;
  for (const p of pieces) {
    if (!p.theme) {
      db.upsertEntity('pieces', 'piece', p.id, { ...p, theme: 'Klassisk' });
      migrated++;
    }
  }
  if (migrated) console.log(`🔁 Migrerte ${migrated} stykke(r) til tema «Klassisk».`);

  // 3. Klassiske stykker kun ved helt tomt bibliotek
  let seeded = 0;
  if (pieces.length === 0) {
    for (const p of SEED_PIECES) {
      db.upsertEntity('pieces', 'piece', generateId(), { ...p, theme: 'Klassisk', spotifyUrl: '', createdAt: now() });
      seeded++;
    }
  }

  // 4. Pop: legg til låter som ikke finnes fra før (dedupe på artist + låt per tema)
  for (const [themeName, list] of Object.entries(SEED_POP)) {
    const existing = db.listEntities('pieces', { filter: { theme: themeName } });
    const have = new Set(existing.map((p) => normKey(p.composer) + '|' + normKey(p.work)));
    for (const p of list) {
      const key = normKey(p.artist) + '|' + normKey(p.song);
      if (have.has(key)) continue;
      db.upsertEntity('pieces', 'piece', generateId(), {
        theme: themeName,
        composer: p.artist,
        epoch: p.album,
        year: p.year,
        work: p.song,
        movement: '',
        spotifyUrl: '',
        createdAt: now(),
      });
      have.add(key);
      seeded++;
    }
  }
  if (seeded) console.log(`🎵 Seeder ${seeded} stykker i biblioteket.`);
  return { seeded, migrated };
}

module.exports = { seedIfEmpty, SEED_PIECES, SEED_POP, SEED_THEMES };
